In [10]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "employee_id": [101, 102, 103, 104, 105, 105],
    "name": [" Alice ", "BOB", "Charlie  ", None, "Eva", "Eva"],
    "department": ["IT", "HR", "IT", "Finance", "HR", "HR"],
    "salary": [75000, 52000, np.nan, 61000, 58000, 58000],
    "experience": [4, 2, 6, 3, np.nan, np.nan],
    "city": ["Chennai", "Coimbatore", "Chennai", None, "Madurai", "Madurai"]
})

display(df)

   employee_id       name department   salary  experience        city
0          101     Alice          IT  75000.0         4.0     Chennai
1          102        BOB         HR  52000.0         2.0  Coimbatore
2          103  Charlie           IT      NaN         6.0     Chennai
3          104        NaN    Finance  61000.0         3.0         NaN
4          105        Eva         HR  58000.0         NaN     Madurai
5          105        Eva         HR  58000.0         NaN     Madurai

In [2]:
print("Shape:", df.shape)
print("Columns:", df.columns.tolist())
print("Data types:")
print(df.dtypes)

display(df.describe(include="all").T)

Shape: (6, 6)
Columns: ['employee_id', 'name', 'department', 'salary', 'experience', 'city']
Data types:
employee_id      int64
name               str
department         str
salary         float64
experience     float64
city               str
dtype: object

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
employee_id,6.0,NaN,NaN,NaN,103.333333,1.632993,101.0,102.25,103.5,104.75,105.0
name,5,4,Eva,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
department,6,3,HR,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
salary,5.0,NaN,NaN,NaN,60800.0,8584.870413,52000.0,58000.0,58000.0,61000.0,75000.0
experience,4.0,NaN,NaN,NaN,3.75,1.707825,2.0,2.75,3.5,4.5,6.0
city,5,3,Chennai,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
missing_report = pd.DataFrame({
    "missing_count": df.isna().sum(),
    "missing_percentage": (df.isna().mean() * 100).round(2)
})

display(missing_report)

             missing_count  missing_percentage
employee_id              0                0.00
name                     1               16.67
department               0                0.00
salary                   1               16.67
experience               2               33.33
city                     1               16.67

In [4]:
print("Duplicates before:", df.duplicated().sum())

df = df.drop_duplicates(subset=["employee_id"], keep="first")

print("Duplicates after:", df.duplicated(subset=["employee_id"]).sum())
display(df)

Duplicates before: 1
Duplicates after: 0

   employee_id     name department   salary  experience        city
0          101   Alice          IT  75000.0         4.0     Chennai
1          102      BOB         HR  52000.0         2.0  Coimbatore
2          103  Charlie         IT      NaN         6.0     Chennai
3          104      NaN    Finance  61000.0         3.0         NaN
4          105      Eva         HR  58000.0         NaN     Madurai

In [12]:
df.columns = df.columns.str.strip().str.lower()

df["name"] = df["name"].astype("string").str.strip().str.title()
df["department"] = df["department"].astype("string").str.strip().str.title()
df["city"] = df["city"].astype("string").str.strip().str.title()

display(df)

   employee_id     name department   salary  experience        city
0          101    Alice         It  75000.0         4.0     Chennai
1          102      Bob         Hr  52000.0         2.0  Coimbatore
2          103  Charlie         It      NaN         6.0     Chennai
3          104     <NA>    Finance  61000.0         3.0        <NA>
4          105      Eva         Hr  58000.0         NaN     Madurai
5          105      Eva         Hr  58000.0         NaN     Madurai

In [6]:
df["name"] = df["name"].fillna("Unknown")
df["department"] = df["department"].fillna("Unassigned")
df["city"] = df["city"].fillna("Unknown")

df["salary"] = df["salary"].fillna(
    df.groupby("department")["salary"].transform("median")
)

df["experience"] = df["experience"].fillna(
    df["experience"].median()
)

display(df)
print("Remaining missing values:")
print(df.isna().sum())

   employee_id     name department   salary  experience        city
0          101    Alice         It  75000.0         4.0     Chennai
1          102      Bob         Hr  52000.0         2.0  Coimbatore
2          103  Charlie         It  75000.0         6.0     Chennai
3          104  Unknown    Finance  61000.0         3.0     Unknown
4          105      Eva         Hr  58000.0         3.5     Madurai

Remaining missing values:
employee_id    0
name           0
department     0
salary         0
experience     0
city           0
dtype: int64

In [7]:
df["employee_id"] = df["employee_id"].astype("int64")
df["salary"] = pd.to_numeric(df["salary"], errors="coerce")
df["experience"] = pd.to_numeric(df["experience"], errors="coerce")

assert df["employee_id"].is_unique
assert df["salary"].notna().all()
assert df["salary"].ge(0).all()

print("Data quality checks passed.")

Data quality checks passed.

In [8]:
df["annual_salary"] = df["salary"]
df["monthly_salary"] = (df["annual_salary"] / 12).round(2)

df["experience_level"] = pd.cut(
    df["experience"],
    bins=[-1, 2, 5, np.inf],
    labels=["Junior", "Mid-Level", "Senior"]
)

display(df)

,employee_id,name,department,salary,experience,city,annual_salary,monthly_salary,experience_level
0,101,Alice,It,75000.0,4.0,Chennai,75000.0,6250.00,Mid-Level
1,102,Bob,Hr,52000.0,2.0,Coimbatore,52000.0,4333.33,Junior
2,103,Charlie,It,75000.0,6.0,Chennai,75000.0,6250.00,Senior
3,104,Unknown,Finance,61000.0,3.0,Unknown,61000.0,5083.33,Mid-Level
4,105,Eva,Hr,58000.0,3.5,Madurai,58000.0,4833.33,Mid-Level

In [14]:
df = df.sort_values("salary", ascending=False)

display(df)

df.to_csv("cleaned_employees.csv", index=False)
print("Saved cleaned_employees.csv")

   employee_id     name department   salary  experience        city
0          101    Alice         It  75000.0         4.0     Chennai
3          104     <NA>    Finance  61000.0         3.0        <NA>
4          105      Eva         Hr  58000.0         NaN     Madurai
5          105      Eva         Hr  58000.0         NaN     Madurai
1          102      Bob         Hr  52000.0         2.0  Coimbatore
2          103  Charlie         It      NaN         6.0     Chennai

Saved cleaned_employees.csv