In [1]:
import pandas as pd
import numpy as np

sales = pd.DataFrame({
    "region": [
        "South", "North", "South", "East", "West",
        "North", "East", "West", "South", "North"
    ],
    "product": [
        "Laptop", "Phone", "Phone", "Laptop", "Tablet",
        "Laptop", "Phone", "Tablet", "Laptop", "Phone"
    ],
    "quantity": [2, 5, 3, 1, 4, 3, 8, 2, 1, 6],
    "unit_price": [50000, 20000, 20000, 50000, 15000,
                   50000, 20000, 15000, 50000, 20000],
    "discount": [0.05, 0.10, 0.00, 0.05, 0.10,
                 0.00, 0.05, 0.00, 0.10, 0.05]
})

sales["revenue"] = (
    sales["quantity"] * sales["unit_price"] * (1 - sales["discount"])
)

display(sales)

  region product  quantity  unit_price  discount   revenue
0  South  Laptop         2       50000      0.05   95000.0
1  North   Phone         5       20000      0.10   90000.0
2  South   Phone         3       20000      0.00   60000.0
3   East  Laptop         1       50000      0.05   47500.0
4   West  Tablet         4       15000      0.10   54000.0
5  North  Laptop         3       50000      0.00  150000.0
6   East   Phone         8       20000      0.05  152000.0
7   West  Tablet         2       15000      0.00   30000.0
8  South  Laptop         1       50000      0.10   45000.0
9  North   Phone         6       20000      0.05  114000.0

In [2]:
print("Total revenue:", sales["revenue"].sum())
print("Average revenue:", sales["revenue"].mean())
print("Maximum revenue:", sales["revenue"].max())
print("Minimum revenue:", sales["revenue"].min())

Total revenue: 837500.0
Average revenue: 83750.0
Maximum revenue: 152000.0
Minimum revenue: 30000.0

In [3]:
region_summary = sales.groupby("region").agg(
    total_revenue=("revenue", "sum"),
    average_revenue=("revenue", "mean"),
    total_quantity=("quantity", "sum"),
    transaction_count=("product", "size")
).round(2)

display(region_summary.sort_values("total_revenue", ascending=False))

        total_revenue  average_revenue  total_quantity  transaction_count
region
North        354000.0        118000.00              14                  3
South        200000.0         66666.67               6                  3
East         199500.0         99750.00               9                  2
West          84000.0         42000.00               6                  2

In [4]:
region_product = sales.groupby(["region", "product"]).agg(
    revenue=("revenue", "sum"),
    units_sold=("quantity", "sum")
).reset_index()

display(region_product)

  region product   revenue  units_sold
0   East  Laptop   47500.0           1
1   East   Phone  152000.0           8
2  North  Laptop  150000.0           3
3  North   Phone  204000.0          11
4  South  Laptop  140000.0           3
5  South   Phone   60000.0           3
6   West  Tablet   84000.0           6

In [5]:
sales["region_total"] = sales.groupby("region")["revenue"].transform("sum")
sales["region_average"] = sales.groupby("region")["revenue"].transform("mean")

sales["share_of_region_revenue"] = (
    sales["revenue"] / sales["region_total"] * 100
).round(2)

display(sales)

,region,product,quantity,unit_price,discount,revenue,region_total,region_average,share_of_region_revenue
0,South,Laptop,2,50000,0.05,95000.0,200000.0,66666.666667,47.50
1,North,Phone,5,20000,0.10,90000.0,354000.0,118000.000000,25.42
2,South,Phone,3,20000,0.00,60000.0,200000.0,66666.666667,30.00
3,East,Laptop,1,50000,0.05,47500.0,199500.0,99750.000000,23.81
4,West,Tablet,4,15000,0.10,54000.0,84000.0,42000.000000,64.29
5,North,Laptop,3,50000,0.00,150000.0,354000.0,118000.000000,42.37
6,East,Phone,8,20000,0.05,152000.0,199500.0,99750.000000,76.19
7,West,Tablet,2,15000,0.00,30000.0,84000.0,42000.000000,35.71
8,South,Laptop,1,50000,0.10,45000.0,200000.0,66666.666667,22.50
9,North,Phone,6,20000,0.05,114000.0,354000.0,118000.000000,32.20

In [10]:
large_regions = sales.groupby("region").filter(
    lambda group: group["revenue"].sum() > 100000
)

display(large_regions.sort_values("revenue", ascending=False))

,region,product,quantity,unit_price,discount,revenue,region_total,region_average,share_of_region_revenue,product_rank_in_region
6,East,Phone,8,20000,0.05,152000.0,199500.0,99750.000000,76.19,1.0
5,North,Laptop,3,50000,0.00,150000.0,354000.0,118000.000000,42.37,1.0
9,North,Phone,6,20000,0.05,114000.0,354000.0,118000.000000,32.20,2.0
0,South,Laptop,2,50000,0.05,95000.0,200000.0,66666.666667,47.50,1.0
1,North,Phone,5,20000,0.10,90000.0,354000.0,118000.000000,25.42,3.0
2,South,Phone,3,20000,0.00,60000.0,200000.0,66666.666667,30.00,2.0
3,East,Laptop,1,50000,0.05,47500.0,199500.0,99750.000000,23.81,2.0
8,South,Laptop,1,50000,0.10,45000.0,200000.0,66666.666667,22.50,3.0

In [11]:
sales["product_rank_in_region"] = (
    sales.groupby("region")["revenue"]
    .rank(method="dense", ascending=False)
)

display(
    sales.sort_values(["region", "product_rank_in_region"])
)

,region,product,quantity,unit_price,discount,revenue,region_total,region_average,share_of_region_revenue,product_rank_in_region
6,East,Phone,8,20000,0.05,152000.0,199500.0,99750.000000,76.19,1.0
3,East,Laptop,1,50000,0.05,47500.0,199500.0,99750.000000,23.81,2.0
5,North,Laptop,3,50000,0.00,150000.0,354000.0,118000.000000,42.37,1.0
9,North,Phone,6,20000,0.05,114000.0,354000.0,118000.000000,32.20,2.0
1,North,Phone,5,20000,0.10,90000.0,354000.0,118000.000000,25.42,3.0
0,South,Laptop,2,50000,0.05,95000.0,200000.0,66666.666667,47.50,1.0
2,South,Phone,3,20000,0.00,60000.0,200000.0,66666.666667,30.00,2.0
8,South,Laptop,1,50000,0.10,45000.0,200000.0,66666.666667,22.50,3.0
4,West,Tablet,4,15000,0.10,54000.0,84000.0,42000.000000,64.29,1.0
7,West,Tablet,2,15000,0.00,30000.0,84000.0,42000.000000,35.71,2.0

In [15]:
pivot = pd.pivot_table(
    sales,
    index="region",
    columns="product",
    values="revenue",
    aggfunc="sum",
    fill_value=0,
    margins=True
)

display(pivot)

product    Laptop     Phone   Tablet       All
region
East      47500.0  152000.0      0.0  199500.0
North    150000.0  204000.0      0.0  354000.0
South    140000.0   60000.0      0.0  200000.0
West          0.0       0.0  84000.0   84000.0
All      337500.0  416000.0  84000.0  837500.0

In [9]:
best_region = region_summary["total_revenue"].idxmax()
best_product = sales.groupby("product")["revenue"].sum().idxmax()

print("Highest-revenue region:", best_region)
print("Highest-revenue product:", best_product)

region_summary.to_csv("regional_aggregation.csv")

Highest-revenue region: North
Highest-revenue product: Phone